SELECT TRIM(LEADING '0' FROM DATE_FORMAT(DATETIME, "%H")) AS HOUR, 
COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE TIME_FORMAT(DATETIME, "%H:%I") BETWEEN '09:00' AND '19:59'
GROUP BY DATE_FORMAT(DATETIME, "%H")
ORDER BY DATE_FORMAT(DATETIME, "%H");